package Test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class AddAddressTest {
	
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;

@Before
public void setUp() {

 System.setProperty("webdriver.chrome.driver", "C:\\Users\\Marija Markovic\\Downloads\\chromedriver.exe");  
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}

@After
public void tearDown() {
 driver.quit();
}

@Test
public void addAddress() {

 driver.get("https://www.opposite-fashion.com/");
 driver.manage().window().setSize(new Dimension(1366, 728));
 driver.findElement(By.cssSelector(".b-close")).click();
 {
   WebElement element = driver.findElement(By.cssSelector("#pt_menu489 > .parentMenu > a"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 {
   WebElement element = driver.findElement(By.cssSelector(".menu-dropit"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.xpath("//a[contains(text(),'Prijava i registracija')]")).click();
 driver.get("https://www.opposite-fashion.com/customer/account/login/");
 driver.findElement(By.id("email")).sendKeys("marijaamarkovic21@gmail.com");
 driver.findElement(By.id("pass")).click();
 driver.findElement(By.id("pass")).sendKeys("142017Marija");
 driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
 driver.get("https://www.opposite-fashion.com/customer/account/");
 driver.findElement(By.xpath("//a[contains(text(),'Vaše adrese')]")).click();
 driver.get("https://www.opposite-fashion.com/customer/address/");
 driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
 driver.get("https://www.opposite-fashion.com/customer/address/new/");
 driver.findElement(By.id("telephone")).click();
 driver.findElement(By.id("telephone")).sendKeys("0632551309");
 driver.findElement(By.id("street_1")).click();
 driver.findElement(By.id("street_1")).sendKeys("Kralja Petra 15");
 driver.findElement(By.id("city")).click();
 driver.findElement(By.id("city")).sendKeys("Cacak");
 driver.findElement(By.id("zip")).click();
 driver.findElement(By.id("zip")).sendKeys("32000");
 driver.findElement(By.cssSelector("span > span")).click();

 driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
 
 //Provera da li je dodata adresa  
 String ocekivani = driver.findElement(By.xpath("//li[contains(.,'The address has been saved.')]")).getText();
 String realni = "The address has been saved.";
 
 assertEquals(ocekivani, realni);
}

}
