package Test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RemoveProductsFromCartTest {
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	 
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\Marija Markovic\\Downloads\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
 
  }
  
  @After
  public void tearDown() {
	driver.quit();
  }
 
  @Test
  public void removeProductsFromCart() {
	  
    driver.get("https://www.opposite-fashion.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".b-close")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".menu-dropit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//a[contains(.,'Prijava i registracija')]")).click();
    driver.get("https://www.opposite-fashion.com/customer/account/login/");
    driver.findElement(By.id("email")).sendKeys("marijaamarkovic21@gmail.com");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("142017Marija");
    
    driver.findElement(By.cssSelector("#send2 > span > span")).click();
    driver.get("https://www.opposite-fashion.com/customer/account/login/");
    driver.findElement(By.xpath("//div[@id='mini_cart_block']/div/div/div/a")).click();
    driver.get("https://www.opposite-fashion.com/checkout/cart/");
    driver.findElement(By.xpath("//button[@id='empty_cart_button']/span/span")).click();
 
    // Niz provera korpe (da li je prazna)
    
    String provera = driver.findElement(By.xpath("//h1[contains(.,'Vaša korpa je prazna.')]")).getText();
    String poruka = "Vaša korpa je prazna.";
    
    assertEquals(provera, poruka);
    
    String prazna = driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/p")).getText();
    String proizvod = "Nemate proizvoda u korpi.";
    
    assertEquals(prazna, proizvod);
    
    String cart = driver.findElement(By.cssSelector(".top-cart-title > a")).getText();
    String real = "0";
    
    assertEquals(cart, real);
    
  }
}
