package Test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class ThreeProductsTest {
  
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  
  public void setUp() {
  
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\Marija Markovic\\Downloads\\chromedriver.exe");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  
  }
  
  @After
  
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  
  public void threeProducts() {
  
	 driver.get("https://www.opposite-fashion.com/");
	 driver.manage().window().setSize(new Dimension(1366, 728));
	 driver.findElement(By.cssSelector(".b-close")).click();
	    
	 {
	   WebElement element = driver.findElement(By.cssSelector(".menu-dropit"));
	   Actions builder = new Actions(driver);
	   builder.moveToElement(element).perform();
	 }
	    
	 driver.findElement(By.xpath("//a[contains(text(),'Prijava i registracija')]")).click();
	 driver.get("https://www.opposite-fashion.com/customer/account/login/");
	 driver.findElement(By.id("email")).sendKeys("marijaamarkovic21@gmail.com");
	 driver.findElement(By.id("pass")).click();
	 driver.findElement(By.id("pass")).sendKeys("142017Marija");
	 driver.findElement(By.cssSelector("#send2 > span > span")).click();
	 driver.get("https://www.opposite-fashion.com/customer/account/login/");
    
    {
      WebElement element = driver.findElement(By.cssSelector("#pt_menu152 > .parentMenu span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    
    driver.findElement(By.xpath("//div[@id='block1152']/div/div/a[10]/span")).click();
    driver.get("https://www.opposite-fashion.com/zenska-obuca/snegarice.html");
    //js.executeScript("window.scrollTo(0, 143)");
    driver.findElement(By.cssSelector(".products-grid:nth-child(3) > .col-xl-3:nth-child(1) .product-image img")).click();
    driver.get("https://www.opposite-fashion.com/zenska-obuca/snegarice/zenske-cizme-lh051750.html");
    driver.findElement(By.xpath("//div[3]/img")).click();
    driver.findElement(By.xpath("//div[@id='amconf-image-221']")).click();
    driver.findElement(By.cssSelector(".button > span > span")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    
    //Provera da li su željene èizme u korpi  
    
    String ocekivane = driver.findElement(By.cssSelector(".success-msg")).getText();
    String realne = "Ženske èizme - LH051750 je dodat u vašu korpu.";
    
    assertEquals(ocekivane, realne);
    
    driver.get("https://www.opposite-fashion.com/checkout/cart/");
    
    driver.findElement(By.xpath("//img[@alt='Opposite Shoes']")).click();
    driver.get("https://www.opposite-fashion.com/");
    driver.findElement(By.cssSelector(".b-close")).click();
    
    {
      WebElement element = driver.findElement(By.cssSelector("#pt_menu152 > .parentMenu span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    
    driver.findElement(By.xpath("//a[4]/span")).click();
    driver.get("https://www.opposite-fashion.com/zenska-obuca/zenske-cizme.html");
    js.executeScript("window.scrollTo(0,103)");
    driver.findElement(By.linkText("3")).click();
    driver.get("https://www.opposite-fashion.com/zenska-obuca/zenske-cizme.html?p=3");
    driver.findElement(By.cssSelector(".col-xl-3:nth-child(2) > .item-inner:nth-child(1) .product-image img")).click();
    driver.get("https://www.opposite-fashion.com/zenske-cizme-lx96006.html");
    driver.findElement(By.id("amconf-image-222")).click();
    driver.findElement(By.cssSelector(".btn-cart > span > span")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
   
    //Provera da li su željene èizme u korpi
    
    String ocekivaneC = driver.findElement(By.cssSelector(".success-msg")).getText();
    String realneC = "Ženske èizme - LX96006 je dodat u vašu korpu.";
    
    assertEquals(ocekivaneC, realneC);
    
    driver.get("https://www.opposite-fashion.com/checkout/cart/");
    
   {
      WebElement element = driver.findElement(By.cssSelector("#pt_menu489 > .parentMenu span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    
    driver.findElement(By.xpath("//div[5]/div[2]/div/div/div/a[2]/span")).click();
    driver.get("https://www.opposite-fashion.com/zenske-torbe/zenski-rancevi.html");
    driver.findElement(By.cssSelector(".products-grid:nth-child(5) > .col-xl-3:nth-child(3) .product-image img")).click();
    driver.get("https://www.opposite-fashion.com/zenske-torbe/zenski-rancevi/zenski-rancevi-t020106-1.html"); 
    driver.findElement(By.cssSelector(".btn-cart > span > span")).click();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    
    // Provera da li je ispravan ranac u korpi
    
    String oRanac = driver.findElement(By.cssSelector(".success-msg")).getText();
    String rRanac = "Ženski ranèevi - T020106-1 je dodat u vašu korpu.";
    
    assertEquals(oRanac, rRanac);
   
    driver.get("https://www.opposite-fashion.com/checkout/cart/");
    
    // Proverava da li je broj proizvoda u korpi ispravan
    
    String three = driver.findElement(By.cssSelector(".top-cart-title > a")).getText();
    String real = "3";
    
    assertEquals(three, real);
    
    //driver.findElement(By.cssSelector("#empty_cart_button > span > span")).click();
    
  }
}

